services:
  postgres:
    container_name: postgres-sql-once
    image: postgres:latest
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA:  /var/lib/postgresql/data
      POSTGRES_DB: once
    volumes:
       - postgres:/data/postgres
    ports:
       - "5432:5432"
    networks:
        - once-network
    restart: unless-stopped

  keycloak:
    container_name: keycloak-once
    image: quay.io/keycloak/keycloak:24.0.3
    ports:
      - "9090:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL_HOST: postgres-sql-once
      KC_DB_URL_DATABASE: once
      KC_DB_USERNAME: username
      KC_DB_PASSWORD: password
    networks:
        - once-network
    command: [ "start-dev"]

networks:
  once-network:
    driver: bridge

volumes:
  postgres:
    driver: local